### ISSUE TITLE
flv2mp4.js中对于config处理产生的错误

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee-flv2fmp4#5]
https://github.com/Chimeejs/chimee-flv2fmp4/blob/master/src/flv2fmp4.js#L20

在这段中，this._config直接被后者覆盖，但在chimee-kernel-flv中依赖的时候是Object.assign，此处config传参是可能为空的，会导致后续new MP4Remuxer的时候报错（MP4Remuxer中会使用config.isLive传参判断初始值）

**Comment by songguangyu** [comment]
已合并，感谢天翔
